### ISSUE TITLE
Bug affichage

### ISSUE THREAD

**Issue by daganM** [juliendargelos/BetterSched#2]
L'affichage des semaines (en général sur le mercredi et jeudi) est bogué.

**Comment by juliendargelos** [comment]
Est-ce que je peux avoir un screen et ta configuration s'il-te-plaît ?

**Comment by daganM** [comment]
![bettersched](https://cloud.githubusercontent.com/assets/12173573/10711759/1ac6fc26-7a86-11e5-9bd2-5df7310c3a8d.png)
Après la quasi-correction, le Jeudi se décale aussi.

**Comment by juliendargelos** [comment]
Merci, je m'en occupe très vite.

**Comment by juliendargelos** [comment]
J'ai réglé le problème, ça fonctionne chez toi ?

**Comment by daganM** [comment]
Yep ça marche :)

**Comment by daganM** [comment]
![bettersched](https://cloud.githubusercontent.com/assets/12173573/10870731/21f738a6-80d2-11e5-8be0-7f374ea923f7.png)
